music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
     # /music/
    url(r'^$', views.index, name='index' ),
     #/music/album_id/

    url(r'^(?P<album_id>[0-9]+)/$',views.detail, name="detail"),

#/music/album_id/favorite
  url(r'^(?P<album_id>[0-9]+)/favorite/$',views.favorite, name="favorite"),
]

project_1/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

music/models.py
from django.db import models

class Album(models.Model):
    artist = models.CharField(max_length=250)
    artist_title = models.CharField(max_length=220)
    genre = models.CharField(max_length=250)
    album_logo = models.CharField(max_length=240)
    def __str__(self):
        return self.artist_title +  '-' + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=240)
    song_title = models.CharField(max_length=240)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/views.py
from django.shortcuts import render, get_object_or_404
from .models import Album,Song

def index(request):
    all_albums = Album.objects.all()
    return render(request, 'music/index.html' , {'all_albums': all_albums})

def detail(request, album_id):
    # album=Album.objects.get(id=album_id)
    album = get_object_or_404(Album, pk=album_id)
    return render(request, 'music/detail.html', {'album': album})

def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk=int(request.POST['song']))
    except(KeyError, Song.DoesNotExist):
        return render(request,'music/detail.html',{
            'album': album,
            'error_message':"You didn't delect a valid song,"
        })
    else:
        selected_song.is_favorite = True
        selected_song.save()
        return render(request, 'music/detail.html', {'album':album})

music/templates/music/detail.html
{%  load staticfiles %}
<img src="{{ album.album_logo }}">

<h1> {{ album.artist_title }}</h1>

<h3>{{ album.artist }}</h3>

{% if error_message %}
         <p> <strong> {{ error_message }}</strong></p>
{% endif %}


<form action="{% url 'music:favorite' album.id %}" method="post">
       {% csrf_token %}
       {% for song in album.song_set.all %}
           <input type="radio" id="song{{  forloop.counter }}" name="song" value="{{song.id}}">
           <label for="song{{ forloop.counter }}">
             {{ song.song_title }}
           {% if song.is_favorite %}
                 <img src="{% static 'music/img.png' %}" >
        {% endif %}

           </label> <br>
    {% endfor %}
<input type="submit" value="Favorite">


</form>

music/templates/music/index.html
{%  if all_albums %}
        <ul>
            {% for album in all_albums %}
             <li><a href="{% url 'music:detail' album.id %}"> {{ album.artist_title }} </a></li>
            {% endfor %}
        </ul>
{% else %}
     <h3>You don't have any albums</h3>

{% endif %}